CodingEvents/Models/ErrorViewModel.cs
namespace CodingEvents.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CodingEvents/Models/Event.cs
namespace CodingEvents.Models
{
    public class Event
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string ContactEmail { get; set; }
        public EventType Type { get; set; }
        public int Id { get; set; }
        public Event()
        {
        }
        public Event(string name, string description, string contactEmail)
        {
            Name = name;
            Description = description;
            ContactEmail = contactEmail;
        }
        public override string ToString()
        {
            return Name;
        }
        public override bool Equals(object? obj)
        {
            return obj is Event @event &&
                   Id == @event.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

CodingEvents/Models/EventCategory.cs
namespace CodingEvents.Models
{
    public class EventCategory
    {
        public int Id { get; set; } 
        public string Name { get; set; }
        public EventCategory()
        {

        }
        public EventCategory(string name)
        {
            Name = name;
        }
    }
}

CodingEvents/Models/EventType.cs
namespace CodingEvents.Models
{
    public enum EventType
    {
          Conference,
          Meetup,
          Workshop,
          Social
    }
}

CodingEvents/ViewModels/AddEventCategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CodingEvents.ViewModels
{
    public class AddEventCategoryViewModel
    {
        [Required]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Name must be between 3 and 20 characters long.")]
        public string Name { get; set; }
    }
}

CodingEvents/ViewModels/AddEventViewModel.cs
using CodingEvents.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace CodingEvents.ViewModels
{
    public class AddEventViewModel
    {
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Name must be between 3 and 50 characters.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter a description for your event.")]
        [StringLength(500, ErrorMessage = "Description must be less than 500 characters.")]
        public string Description { get; set; }

        [EmailAddress]
        [Required]
        public string ContactEmail { get; set; }

        public EventType Type { get; set; }

        public List<SelectListItem> EventTypes { get; set; } = new List<SelectListItem>
        {
            new SelectListItem(EventType.Conference.ToString(), ((int)EventType.Conference).ToString()),
            new SelectListItem(EventType.Meetup.ToString(), ((int)EventType.Meetup).ToString()),
            new SelectListItem(EventType.Workshop.ToString(), ((int)EventType.Workshop).ToString()),
            new SelectListItem(EventType.Social.ToString(), ((int)EventType.Social).ToString()),
        };
    }
}

CodingEvents/Controllers/EventCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using CodingEvents.Data;
using CodingEvents.Models;
using CodingEvents.ViewModels;

namespace CodingEvents.Controllers
{
    public class EventCategoryController : Controller
    {
        public EventDbContext context;

        public EventCategoryController(EventDbContext dbContext) { this.context = dbContext; }

        //GET /<controller>/
        public IActionResult Index()
        {
            ViewBag.title = "All Categories";
            List<EventCategory> categories = context.Categories.ToList();
            return View(categories);
        }

        //GET /<controller>/create
        public IActionResult Create()
        {
            return View(new AddEventCategoryViewModel());
        }

        //POST /<controller>/
        [HttpPost("/create")]
        public IActionResult ProcessCreateEventCategoryForm(AddEventCategoryViewModel addEventCategoryViewModel)
        {
            if(ModelState.IsValid)
            {
                EventCategory newEventCategory = new EventCategory();
                newEventCategory.Name = addEventCategoryViewModel.Name;
                context.Categories.Add(newEventCategory);
                context.SaveChanges();
                return Redirect("/eventcategory");
            }
            return Redirect("/eventcategory/create");
        }
    }
}

CodingEvents/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using CodingEvents.Models;
using CodingEvents.Data;
using CodingEvents.ViewModels;
using Microsoft.AspNetCore.CookiePolicy;
using System.Linq;

namespace CodingEvents.Controllers
{
    public class EventsController : Controller
    {
        private EventDbContext context;

        public EventsController(EventDbContext dbContext)
        {
            this.context = dbContext;
        }
        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            List<Event> events = context.Events.ToList();

            return View(events);
        }

        // GET: /<controller>/add
        public IActionResult Add()
        {
            AddEventViewModel addEventViewModel = new AddEventViewModel();

            return View(addEventViewModel);
        }

        //POST : /<controller>/add
        [HttpPost]
        public IActionResult Add(AddEventViewModel addEventViewModel)
        {
            if(ModelState.IsValid)
            {
                Event newEvent = new Event
                {
                    Name = addEventViewModel.Name,
                    Description = addEventViewModel.Description,
                    ContactEmail = addEventViewModel.ContactEmail,
                    Type = addEventViewModel.Type
                };
                context.Events.Add(newEvent);
                context.SaveChanges();

                return Redirect("/events");
            }
            return View(addEventViewModel);
        }

        // GET: /<controller>/delete
        public IActionResult Delete()
        {
            ViewBag.events = context.Events.ToList();
            return View();
        }

        // POST: /<controller>/delete
        [HttpPost]
        public IActionResult Delete(int[] eventIds)
        {
            foreach(int eventId in eventIds)
            {
                Event theEvent = context.Events.Find(eventId);
                context.Events.Remove(theEvent);
            }
            context.SaveChanges();
            return Redirect("/events");
        }

        //GET : /<controller>/edit
        [HttpGet]
        [Route("/events/edit/{eventId}")]
        public IActionResult Edit(int eventId)
        {
            ViewBag.Event = context.Events.Find(eventId);
            //ViewBag.Event = EventData.GetById(eventId);
            ViewBag.title = $"Edit Event {ViewBag.Event.Name}(id={ViewBag.Event.Id})";
            return View();
        }

        // POST: /<controller>/edit
        [HttpPost("/events/edit")]
        [Route("/events/edit/{eventId}")]
        public IActionResult SubmitEditEventForm(int eventId, string name, string description)
        {
            Event eventToBeEdited = context.Events.Find(eventId);
            eventToBeEdited.Name = name;
            eventToBeEdited.Description = description;
            context.SaveChanges();
            return Redirect("/events");
        }
    }
}

CodingEvents/Controllers/HomeController.cs
using CodingEvents.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CodingEvents.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodingEvents/Views/EventCategory/Create.cshtml
@using CodingEvents.ViewModels;
@model AddEventCategoryViewModel;

<form asp-controller="EventCategory" asp-action="ProcessCreateEventCategoryForm" method="post">
    <div class="form-group">
        <label asp-for="Name">Event Category Name: <input asp-for="Name" type="text"/></label>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <input type="submit" value="Add Event Category"/>
</form>

CodingEvents/Views/EventCategory/Index.cshtml
@model List<EventCategory>


<h1>@ViewBag.title</h1>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
    </tr>
    @foreach(EventCategory category in Model)
    {
        <tr>
            <td>@category.Id</td>
            <td>@category.Name</td>
        </tr>
    }
</table>

CodingEvents/Views/Events/Add.cshtml
@using CodingEvents.ViewModels

@model AddEventViewModel

<h1>Add Event</h1>

<form method="post" asp-controller="Events" asp-action="Add">
    <div class="form-group">
        <label asp-for="Name">Name: <input asp-for="Name" type="text" /></label>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description: <input asp-for="Description"/></label>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ContactEmail">Contact Email: <input asp-for="ContactEmail" /></label>
        <span asp-validation-for="ContactEmail" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type">Event Types: </label>
        <select asp-for="Type" asp-items="Model.EventTypes"></select>
    </div>
    <input type="submit" value="Add Event" />
</form>

CodingEvents/Views/Events/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post">
    @foreach(var evt in ViewBag.events) {
        <div class="form-group">
            <label>
                <span>@evt.Name</span>
                <input type="checkbox" name="eventIds" value="@evt.Id" />
            </label>
        </div>
    }

    <input type="submit" value="Delete Selected Events" class="btn btn-danger"/>
</form>

CodingEvents/Views/Events/Edit.cshtml
<h1>@ViewBag.title</h1>

<form method="post" action="/events/edit">

    <label>Event Name: <input type="text" name="name" value="@ViewBag.Event.Name" /></label>
    <label>Description: <input name="description" value="@ViewBag.Event.Description" /></label>
    <input type="hidden" value="@ViewBag.Event.Id" name="eventId" />
    <input type="submit" value="Edit Event" />
</form>

CodingEvents/Views/Events/Index.cshtml
@using CodingEvents.Models

@model List<Event>

<h2>Coding Events</h2>

<p>
    <a asp-controller="Events" asp-action="Add">Add Event</a>
</p>
<p>
    <a asp-controller="Events" asp-action="Delete">Delete Event</a>
</p>

@if(Model.Count == 0) {
    <p>No events yet!</p>
}
else {
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Event Name</th>
            <th>Description</th>
            <th>Email</th>
            <th>Type</th>
        </tr>
        @foreach (var evt in Model)
        {
            <tr>
                <td>@evt.Id</td>
                <td>@evt.Name</td>
                <td>@evt.Description</td>
                <td>@evt.ContactEmail</td>
                <td>@evt.Type</td>
                <td><a asp-controller="Events" asp-action="Edit" asp-route-id="@evt.Id">Edit Event</a></td>
            </tr>
        }
    </table>

}

CodingEvents/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CodingEvents/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodingEvents</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CodingEvents.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodingEvents</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EventCategory" asp-action="Index">Show Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EventCategory" asp-action="Create">Add Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Show Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Add">Add Event</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CodingEvents - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>